### ISSUE TITLE
Validating current in-built SBOM plugins

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#43]
**Description**
Currently 2 SBOM plugins - SBOM verifier, License checker
Need to check efficiency or capability of SBOMs generated by MS SBOM tool

**Acceptance Criteria**

- [x] Need an image that has an associated SBOM
- [x] Verify that SBOM verifier works as expected with above SBOM - should always pass
- [x] Verify that license checker always fails. JSON based SPDX SBOMs would fail the license checker.
- [x] Verify with Gatekeeper in a Kubernetes cluster.
- [x] Documenting verified capabilities. 
- [x] Documenting any misalignments and creating new Issue if required.
- [x] Share findings with team.

**Comment by kjeffc** [comment]
SBOM verification works as expected
```
{
  "isSuccess": false,
  "verifierReports": [
    {
      "isSuccess": false,
      "name": "notaryv2",
      "message": "an error thrown by the verifier: unsupported SigningScheme: ``",
      "artifactType": "application/vnd.cncf.notary.v2.signature"
    },
    {
      "subject": "sscii7o7zvea7qim.azurecr.io/github/userprofile:eaf84ee",
      "isSuccess": true,
      "name": "sbom",
      "message": "SBOM verification success. The contents is good.",
      "artifactType": "org.example.sbom.v0"
    }
  ]
}
```

Licensechecker fails as expected due to formatting error due to not providing a valid SPDX artifact
```
{
  "isSuccess": false,
  "verifierReports": [
    {
      "isSuccess": false,
      "name": "licensechecker",
      "message": "an error thrown by the verifier: plugin command VERIFY failed; no colon found in '{'",
      "artifactType": "org.example.sbom.v0"
    }
  ]
}
```

**Comment by Joll59** [comment]
Licensechecker fails as expected on a k8s cluster due to formatting error due to not providing
<img width="615" alt="image" src="https://user-images.githubusercontent.com/16693765/202578867-505c86dd-3332-40c4-bdb1-aaf032d86bd0.png">

**Comment by Joll59** [comment]
Full documentation:
https://github.com/cse-labs/ratify/blob/43-sbom-plugins/hack/42-verifiers/sbom.md
