### ISSUE TITLE
Explore current artifact verification loop behavior

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#44]
**Description**
[Current findings reported here](https://teams.microsoft.com/l/message/19:o44WdFLchBq_MdsgLHTwpGw-_DA1YCBe1t6_N-Gq2t01@thread.tacv2/1668116682974?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=a66f455c-de00-4d2c-a80e-de0e9050887d&parentMessageId=1668116682974&teamName=Secure%20Software%20Supply%20Chain%20on%20AKS&channelName=General&createdTime=1668116682974&allowXTenantAccess=false)

Current behaviour:
If verifier cannot verify - execution moves to next verifier
If verifier can verify - execution loop exits
Assumption is that per artifact type there is only one verifier

Expectation:
If verifier cannot verify - execution moves to next verifier
If verifier can verify - execution moves to next verifier

**Acceptance Criteria**
- Update and test code for expected behavior listed above
- Understand impact of this change
- Explore nested artifacts and behavior
- Share finding with team
- Document current behavior
- Understand legitimate scenarios which may require this expected behavior

**Comment by rasavant-ms** [comment]
Current behavior is documented. Pending discussion for expected/desired behavior in design sessions.

**Comment by raymond-nassar** [comment]
https://github.com/cse-labs/ratify/blob/joshuaphelpsms/enable-multiple-verifiers-for-same-type/hack/NOTES.md

Doc created by Josh to document Multiple Verifiers for the same artifact type.
