### ISSUE TITLE
Verify core execution loop behavior

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#45]
**Description:**
A failed verification is treated as if an exception is being thrown.
Policy provider in JSON config - Passthrough mode helps to verify robust policies in rego.

Without passthrough mode expectation is that if validation of subject fails, loop breaks out.
With passthrough mode on, validation failure or exception thrown, loop continues on to next artifact.

**Acceptance Criteria:**

- [x] Verify behavior of execution loop for following scenarios:
  - [x]  execution mode is passthrough
- [x] Discuss with team if current behavior is valid/acceptable
- [x] Documentation

**Comment by rasavant-ms** [comment]
Reference - https://github.com/deislabs/ratify/issues/192

**Comment by mluker** [comment]
@cmaclaughlin @rasavant-ms In support of "Test against image package where notation is not in sync" I pushed [code](https://github.com/mluker/artifact-signing) that will allow the creation of an image signed with notation v0.9. You can now run an ad hoc sample as needed using ./runner sample5 (still need to do step 1-4 in read me)
