### ISSUE TITLE
Write constraints in Rego

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#46]
**Description:**
Currently, constraint templates exist in library folder.

**Acceptance Criteria:**
- Document current constraints
- Goal is to write constraints that meet criteria
   - Each image must be signed
   - Each image must have an SBOM attached. The SBOM must be signed.
   - Each image must have a vulnerability report attached. The report must be signed
- PR into scenario repo

**Comment by Joll59** [comment]
Completed with this [PR](https://github.com/cse-labs/scenario-secure-software-supply-chain-on-aks/pull/83) in the scenario repo.
