### ISSUE TITLE
Plugins as ORAS

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#50]
**Description**
Using Plugins from ACR

**AC**
- Push a plugin to ACR
- Update Ratify to pull images via ORAS
   - At startup when using config.json
   - When registering a new plugin using CRD

**Comment by noelbundick-msft** [comment]
If we want to pick this up, we should try it out, form some opinions, and then

* Post an Issue + join Ratify community call for discussion
* Close it out and decide not to carry this forward

**Comment by noelbundick-msft** [comment]
Discussed at the 2022-12-13 community call, where it was supported. Decision is to move forward with an issue / design doc for tracking, and open a working draft PR based on the initial prototype to gather feedback & ideas

**Comment by noelbundick-msft** [comment]
Primary goal: draft pr out for discussion by 2022-12-21

**Comment by mluker** [comment]
Duplicate of #78
