### ISSUE TITLE
Defining purpose of verifiers

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#51]
**Description:**
Define the purpose of verifiers in current state. What would the purpose of verifiers be in desired state? What should the boundary between responsibility of verifier vs. responsibility of constraint/policy be? _This should probably be done by all groups after there is greater familiarity with the codebase and the different components. Ideally, the whole group would reconcile and agree upon the definitions/boundary of desired state._

**AC**
- Document proposal of design
- Design discussion with team to reach a shared understanding and consensus
- Reviewing community call recording from Nov 15th - [Ratify Community Call 2022 Nov 15 - YouTube](https://www.youtube.com/watch?v=zUYRNli1ufY)

**Comment by cmaclaughlin** [comment]
At a basic level, verifiers are boolean generators. What they do is determined by the verifier plugin and should be documented accordingly to inform customers/users who want to use said plugin.
