### ISSUE TITLE
Verifier that validates SBOM schema

### ISSUE THREAD

**Issue by noelbundick-msft** [cse-labs/ratify#58]
Currently it's possible to jam in nonsense, label it as SPDX, and the SBOM verifier is happy to accept it. We want to validate that artifacts are in the correct format before returning `isSuccess: true`

This is a spike to prove out the idea. We want to start small with a single example/type versus trying to solve the general problem for all possible use cases

**Acceptance Criteria**

* New verifier plugin that uses JSON-Schema to validate documents
* Uses a hardcoded schema for `application/spdx+json`
  * The idea is that in the future, you might specify schema via config, but don't dump a lot of time on that - keep it simple

https://github.com/cse-labs/ratify/issues/58#tasklist-block-1c193ef4-7566-4e3d-8cf7-a4714494fa42

**Comment by rasavant-ms** [comment]
Formats for SBOMs - SPDX (json, xml), CycloneDX (json, xml)
- [ ] List all artifact formats that we want to validate - Probably only SPDX with json. What about xml?
- [ ] Create new plugin
- [ ] Create a basic schema for application/spdx+json
- [ ] Use third party tool to verify spdx format in json?
- [ ] Call new plugin only for spdx+json format

**Comment by stevespringett** [comment]
The CycloneDX validation should be super simple. But if you have any questions, please reach out to me or the CDX community. We’d be glad to help.

**Comment by rasavant-ms** [comment]
Thanks @stevespringett !
We would love to hear about how customers currently validate their CDX SBOMs?
What verifications would benefit customers using CycloneDX?

**Comment by stevespringett** [comment]
* Many CycloneDX implementations validate a BOM after its created to ensure it's compliant. The Java Maven and Gradle plugins does this for example.
* Others use the [CycloneDX CLI](https://github.com/CycloneDX/cyclonedx-cli) to perform the validation.
* And others simply use any XML Schema or JSON Schema validation tool. CycloneDX does not require additional validation on top of what XML or JSON schema already provide. This is in stark contrast with SPDX which does require additional validation.

For future reference, the [OWASP Software Component Verification Standard](https://scvs.owasp.org/) is currently working on a [BOM Maturity Model](https://scvs.owasp.org/bom-maturity-model/). The model is format agnostic and includes capabilities of CDX, SPDX, and things that neither currently support. Once complete (targeting Q2 2023), we envision a new breed of tools to emerge: BOM Profilers, which would be able to inspect a BOM and let you know what types of analysis can be performed on it. We'll also see the emergence of policy around BOM profiles for various use cases.

**Comment by mluker** [comment]
blocked by [upstream issue](https://github.com/deislabs/ratify/issues/504)

**Comment by rasavant-ms** [comment]
https://github.com/deislabs/ratify/pull/536

**Comment by rasavant-ms** [comment]
Closing since https://github.com/deislabs/ratify/pull/536 is closed and merged
