### ISSUE TITLE
Evaluate removal of passthrough mode

### ISSUE THREAD

**Issue by noelbundick-msft** [cse-labs/ratify#63]
Passthrough mode used to be important & impacted control flow. Now, it only forces the top-level `isSuccess` property to `true`

It may not be needed anymore. Figure it out, make a recommendation in Ratify issues + community call (or close this)

**Comment by rasavant-ms** [comment]
Issue - https://github.com/deislabs/ratify/issues/474

**Comment by rasavant-ms** [comment]
completed via [#494](https://github.com/deislabs/ratify/pull/494)
