### ISSUE TITLE
Verify/fix Ratify helm deployment updates

### ISSUE THREAD

**Issue by mluker** [cse-labs/ratify#74]
Just tested out changing helm values and running helm upgrade and seems to work fine. Interested to hear if anyone is still having issues with this. - Josh (not sure why it is not allowing me to add my own comment so it looks like Noel wrote this but he did not)

**Comment by mluker** [comment]
Although I've experienced hanging installs|upgrades in the past,  I just ran through ~30 installs|upgrades|uninstalls and it went smooth every time.

**Comment by rasavant-ms** [comment]
Workaround updated in docs #75
