### ISSUE TITLE
Base documentation for Ratify new users

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#75]
**Description**
Create clean documentation for new Ratify user to get up and running.

**Acceptance criteria**
* Build off of Luker's existing PR and use the basic steps to get started
*  Add docs to ratify/docs/reference/usage.md
* Update the azure related usage docs - https://github.com/cse-labs/ratify/blob/main/docs/examples/ratify-verify-azure-cmd.md
     * Update versions

**Comment by joshuaphelpsms** [comment]
PR for `docs/examples/ratify-verifiy-azure-cmd.md` changes at https://github.com/deislabs/ratify/pull/545
