### ISSUE TITLE
Updated SBOM Verifier

### ISSUE THREAD

**Issue by cmaclaughlin** [cse-labs/ratify#76]
The existing SBOM verifier plugin checks makes sure "content != bad". 

Updates include:
- Parsing blob with SPDX package
- Handling SPDX json exclusively but tag/xml can easily be added in the future
- Returning specific fields related to document creation via the result `extensions` 

https://github.com/cse-labs/ratify/issues/76#tasklist-block-329fd6dd-cc27-4d70-a81b-422b08f02383

**Comment by rasavant-ms** [comment]
Duplicate - #58
